# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgt', '0004_auto_20180817_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='noOfYears',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course_class',
            name='yearOfCourse',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course_class',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
