# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-18 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgt', '0005_auto_20180818_1834'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course_class',
            table='course_class',
        ),
    ]
