# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentMgt', '0007_auto_20180818_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
    ]
